export const blockGame: string;
export const startGame: string;
export const image: string;
export const descriptionGame: string;
export const heading: string;
export const content: string;
export const innerContent: string;
export const playButton: string;
export const roundPlay: string;
