export const blue: string;
export const blueGradient: string;
export const container: string;
export const green: string;
export const minimal: string;
export const red: string;
export const transparent: string;
export const white: string;
export const yellow: string;
