export const Routes = {
  Index: '/',
  articles: '/articles',
  newArticles: '/articles/new-articles',
  Schedule: '/schedule',
  Results: '/results',
  Payment: '/payment',
  Achievements: '/achievements',
  Games: '/games',
  Contacts: '/contacts',
  Students: '/students',
  Signin: '/account/signin',
  Signout: '/account/signout',
  Signup: '/account/signup',
  ForgotPassword: '/account/forgot-password',
  ResetPassword: '/account/reset-password',
  SingleGame: '/single-game',
  TestPage: '/test-page',
};
