export const cell: string;
export const container: string;
export const grid: string;
export const halfHour: string;
export const headerCell: string;
export const innerContainer: string;
export const row: string;
export const rowHeader: string;
export const timeIntervals: string;
