export const select: string;
export const defaultSelect: string;
export const error: string;
export const label: string;
export const labelAfter: string;
export const selectArrow: string;
export const selectWrap: string;
export const selectWrapBox: string;
export const selectWrapBoxAfter: string;
