import CardStudentBottomComponent from '@components/card-student-bottom/CardStudentBottom';
import CardStudentMainButtonComponent from '@components/card-student-main-button/CardStudentMainButton';
import AccountComponent from './account/Account';
import ButtonPlayComponent from './button-play/ButtonPlay';
import ButtonSubmitComponent from './button-submit/ButtonSubmit';
import ButtonComponent from './button/Button';
import CardStudentSliderComponent from './card-student-slider/CardStudentSlider';
import CustomCalendarComponent from './custom-calendar/CustomCalendar';
import CustomImageWrapperComponent from './custom-image-wrapper/CustomImageWrapper';
import CustomSelectComponent from './custom-select/CustomSelect';
import GuardComponent from './guard/Guard';
import HeaderComponent from './header/Header';
import HomeworkComponent from './homework/Homework';
import LayoutComponent from './layout/Layout';
import LogoComponent from './logo/Logo';
import PageContainerComponent from './page-container/PageContainer';
import PageLoadingComponent from './page-loading/PageLoading';
import ProgressBarComponent from './progress-bar/ProgressBar';
import SidebarNavigationItemComponent from './sidebar-navigation-item/SidebarNavigationItem';
import TableComponent from './table/Table';
import TextFieldCalendarComponent from './text-field-calendar/TextFieldCalendar';
import VerticalSliderComponent from './vertical-slider/VerticalSlider';

export const Account = AccountComponent;
export const Button = ButtonComponent;
export const ButtonPlay = ButtonPlayComponent;
export const ButtonSubmit = ButtonSubmitComponent;
export const CustomCalendar = CustomCalendarComponent;
export const CustomImageWrapper = CustomImageWrapperComponent;
export const CustomSelect = CustomSelectComponent;
export const Guard = GuardComponent;
export const Header = HeaderComponent;
export const Homework = HomeworkComponent;
export const Layout = LayoutComponent;
export const Logo = LogoComponent;
export const PageContainer = PageContainerComponent;
export const PageLoading = PageLoadingComponent;
export const ProgressBar = ProgressBarComponent;
export const SidebarNavigationItem = SidebarNavigationItemComponent;
export const Table = TableComponent;
export const TextFieldCalendar = TextFieldCalendarComponent;
export const VerticalSlider = VerticalSliderComponent;
export const CardStudentBottom = CardStudentBottomComponent;
export const CardStudentMainButton = CardStudentMainButtonComponent;
export const CardStudentSlider = CardStudentSliderComponent;
